create database cars;
USE cars
-- READ DATA--
SELECT * from car_dekho;

-- TOTAL COUNTS OF CARS--
SELECT COUNT(*) FROM car_dekho; #7927

-- HOW MANY  CAR WILL BE   AVAILABE IN 2023--
SELECT COUNT(*) FROM car_dekho WHERE YEAR =2023;  # 6

-- HOW MANY  CAR WILL BE   AVAILABE IN 2020,2021,2022--
SELECT  YEAR,COUNT(*) AS TOTAL FROM car_dekho WHERE YEAR IN(2020,2021,2022)GROUP BY YEAR;

-- COUNT OF ALL CARS NOT THE DETALS--
SELECT YEAR,COUNT(*) AS TOTAL FROM CAR_DEKHO GROUP BY YEAR;

-- HOW MANY DIESAL CARS AVAILABE IN YEAR 2020--
SELECT COUNT(*) FROM car_dekho WHERE YEAR= 2020 AND FUEL="DIESEL";  # 20

-- HOW MANY PETROL CARS AVAILABE IN YEAR 2010--
SELECT COUNT(*) FROM car_dekho WHERE YEAR=2010 AND FUEL="PETROL";  # 184

-- TOTAL NUMBER OF FUEL CARS( PETROL, DIESEL , CNG) COME BY ALL YEARS--
SELECT YEAR, COUNT(*) FROM car_dekho WHERE FUEL="DIESEL" GROUP BY YEAR;
SELECT YEAR, COUNT(*) FROM car_dekho WHERE FUEL="PETROL" GROUP BY YEAR;
SELECT YEAR, COUNT(*) FROM car_dekho WHERE FUEL="CNG" GROUP BY YEAR;
                  -- OR --
SELECT YEAR, FUEL ,COUNT(* )FROM car_dekho GROUP BY YEAR, FUEL ;

-- WHICH YEARS HAD MORE THAN 100 CARS --
SELECT YEAR,COUNT(*) FROM car_dekho GROUP BY YEAR HAVING COUNT(*)>100;

-- WHICH YEARS HAD MORE THAN 50 CARS --
SELECT YEAR,COUNT(*) FROM car_dekho GROUP BY YEAR HAVING COUNT(*)<50;

-- TOTAL NUMBER OF CARS BETWEEN 2015 TO 2023 WITH IMPORTANT DETAILS --
SELECT YEAR,FUEL,SELLER_TYPE, OWNER, COUNT(*) AS TOTAL FROM car_dekho WHERE YEAR BETWEEN 2015 AND 2023 GROUP BY YEAR,FUEL,SELLER_TYPE,OWNER;

                               -- END --